# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Fuck! Die 109 ist weg
tagline:          Black Theme for Jekyll
description:      "Die 109 war ein politisches Wohnzimmer zum Austausch, Vernetzen und Organisieren auf der Eisenbahnstraße in Leipzig."
url:              https://hundertneun.net
baseurl:          /
                  # the optional subpath of your site, e.g. "/my-jekyll-site/"
                  # This will apply to all pages in your Jekyll site.

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/my-jekyll-site/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            1.0.1

github:
  url:             https://github.com/reclaim109/reclaim109-website
facebook:
  url:             https://www.facebook.com/politischesWohnzimmer
