# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Fuck! Die 109 ist weg
tagline:          Black Theme for Jekyll
description:      "Die 109 war ein politisches Wohnzimmer zum Austausch, Vernetzen und Organisieren auf der Eisenbahnstraße in Leipzig. Nach vielen Jahren wurde der Mietvertrag jedoch nicht mehr verlängert, sodass wir Ende Juni 2018 die Räume verlassen mussten."
url:              https://hundertneun.net
baseurl:          /
                  # the optional subpath of your site, e.g. "/my-jekyll-site/"
                  # This will apply to all pages in your Jekyll site.

author:
  name:           Karlo Espiritu
  url:            https://twitter.com/karloespiritu

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/my-jekyll-site/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            2.0.1

github:
  repo:             https://github.com/karloespiritu/blackdoc
